#-------------------
#       Guild
#-------------------
# Code bởi Cortez Romeo
# Chia sẻ miễn phí tại minecraftvn.net

# Người chơi vẫn có thể xài lệnh để thao tác nếu như
# enableGUI có giá trị là true
enableGUI: true
# Áp dụng cho việc hiển thị thời gian thành lập hoặc
# gia nhập guild
#   --------------
#   y : năm
#   M : tháng trong năm
#   d : ngày trong tháng
#   E : tên ngày trong tuần (Tiếng Anh)
#   a : định dạng AM hoặc PM 
#   H : giờ trong ngày (0-23)
#   h : giờ AM hoặc PM (1-12)
#   m : phút trong giờ
#   s : giây trong phút
#   -------------- 
# Bạn có thể đổi thành : 
# "Ngày dd tháng MM năm yyyy - HH Giờ mm Phút ss Giây"
# Để cho nó gọn, mình sẽ để:
dateFormat: "dd/MM/yyyy HH:mm:ss"           
              
# Tương tác bằng chat sẽ hiển thị khi người chơi được
# invite hoặc gửi yêu cầu disband,...                               
clickAbleChat:  
  button:
    showButton: true
    # Nút chọn sẽ hiển thị dọc hoặc ngang
    # down : dọc
    # thwart : ngang
    style: thwart
    # Cách dòng
    spacing: 
      thwart: "         "      
      down: "       "
    acceptButton: "&a&l[CHẤP NHẬN]"                    
    denyButton: "&c&l[HỦY]"
    hoverText: 
      acceptButton: "&2Nhấn vào đây để chấp nhận"
      denyButton: "&4Nhấn vào đây để hủy"
      spacing: "&eSuy nghĩ trước khi chọn nhé!"
  endlineEnable: true  
  endline: "&7-------------------------------"
  #
    
rank:
  owner: Chủ Guild
  manager: Quản Lý  
  member: Thành Viên
  
# Kiểu hiển thị khi liệt kê tên những người trong một
# guild
membersNameDisplayType: ", &e%player%&r"
                    
invite:
  # Thời gian để có thể invite tiếp sau lần invite
  # trước đó, nên để gấp đôi expiresTime
  cooldownTime: 10
  # Thời gian để chấp nhận lời mời
  expiresTime: 30
create:
  # Tối đa số ký tự có thể đặt
  maxLength: 10
  # Từ cần nhập để hủy tạo guild khi người chơi tương tác
  # ở GUI
  cancelCreateWords: ?huy
  # Các loại tiền tệ mà người chơi cần có để có thể tạo guild
  # Yêu cầu plugin:
  # + Vault
  # + PlayerPoints
  # + TokenManager
  # Nếu muốn loại một hoặc cả 3 đơn vị tiền tệ, bạn set giá
  # trị của đơn vị đó thành 0
  request:
    money: 100
    point: 100
    token: 100
  # Từ chối các từ để đặt guild sau đây:    
  denyCharacters:
    fullName:
     - admin
     - staff
     - admins
     - staffs
    # Phần "characters" này chỉ nên thêm chứ không nên bớt
    characters:
     - '.'
     - '&'
     - '/'   
     - '\'
     - '|'   
     - ':'
     - '*'        
     - '?'
     - '"'
     - '>'
     - '<'          
     
# Xóa guild
disband:
  # Hình thức xóa guild
  # Khả dụng: GUI hoặc CHAT
  form: GUI
  # Thời gian để có thể disband tiếp sau lần disband
  # trước đó, nên để gấp đôi expiresTime
  cooldownTime: 10
  # Thời gian để xác nhận
  expiresTime: 
    chat: 15
    GUI: 5
    
# Rời guild
leave:
  # Hình thức rời guild
  # Khả dụng: GUI hoặc CHAT
  form: CHAT
  # Thời gian để có thể rời guild tiếp sau lần rời guild
  # trước đó, nên để gấp đôi expiresTime
  cooldownTime: 10
  # Thời gian để xác nhận
  expiresTime: 
    chat: 15
    GUI: 5    
  
# maxLength: Tối đa số ký tự có thể đặt (Bao gồm cả màu &...)
board:
  maxLength: 50
customName:
  maxLength: 25
    